- name: Install ZSH
  become: yes
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
    
- name: Change shell to zsh
  become: yes
  user:
    name: fb
    shell: /bin/zsh
  tags: *tags_for_zsh_tasks

- name: Check that the somefile.conf exists
  stat:
    path: /home/fb/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: not oh_my_stats.stat.exists
  become_user: fb

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

- name: Delete preset conf
  file:
    path: /home/fb/.zshrc
    state: absent
  tags: *tags_for_zsh_tasks
